name: Update Next.js

on:
    schedule:
        # This will run the script every day at 00:00 UTC.
        - cron: '0 0 * * *'

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '*'

        - name: Install npm-check-updates
          run: npm install -g npm-check-updates


        - name: Update All Packages
          run: |
              ncu -u 
              npm install