name: Update Next.js

on:
  schedule:
    # This will run the script every first day of the month at 00:00 UTC.
    - cron: '0 0 1 * *'
        

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '*'
        - name: Install npm-check-updates
          run: npm install -g npm-check-updates

        - name: Update All Packages
          run: |
              ncu -u 
              npm install
        
        - name: Commit and push changes
            git config --global user.email "tanimou@live.fr"
            git config --global user.name "Tanimou Cisse"
          run: |
            git add package*.json
            git diff --staged --quiet || git commit -m "Update all packages"
            git push
